# the site details
title: Sandeep Gupta
tagLine: Keep Walking!

# something about me
author:
  name: Sandeep Gupta
  github: sangupta
  email: sandy.pec@gmail.com
  url: https://sangupta.com

# are we publicly serving
serving_publicly: true

# code syntax highlighter to use
highlighter: rouge
markdown: kramdown

# exclude following files from build
exclude: [ "bower.json", "Gemfile", "Gemfile.lock", "README.md", "package.json" ]

# used to indicate where we split up post and excerpt
excerpt_separator: <!-- break here -->

# file format encodings
encoding: utf-8

# used in sitemap to produce absolute urls
url: https://sangupta.com
domain: sangupta.com

# where all code is kept
# source: /git/sangupta.github.io

# disable custom plugins
safe: true

# pagination options
paginate: 20
paginate_path: "tech/page:num"

# plugins approved to be used
gems:
  - github-pages
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-avatar
