# the site details
title: Sandeep Gupta
tagLine: Keep Walking!

# something about me
author:
  name: Sandeep Gupta
  github: sangupta
  email: sandy.pec@gmail.com
  url: http://sangupta.com

# code syntax highlighter to use
highlighter: pygments
markdown: redcarpet

# used to indicate where we split up post and excerpt
excerpt_separator: <!-- break here -->

# file format encodings
encoding: utf-8

# used in sitemap to produce absolute urls
production_url : http://sangupta.github.io

# where all code is kept
# source: /git/sangupta.github.io

# disable custom plugins
safe: true

# pagination options
paginate: 5
paginate_path: "tech/page:num/"

# plugins approved to be used
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
